dist: xenial   # required for Python >= 3.7

language: python

python:
  - 3.6
  - 3.7

before_install:
  - sudo apt-get update
  - sudo apt-get install -y vlc
  - export AUDIODEV=null

install:
  - pip install -r requirements-dev.txt

before_script:
  - flake8

script:
  - pytest
