[tool.black]
line-length = 120
include = '\.pyi?$'
exclude = '''
/(
    .git
  | .dndj_cache
  | .pytest_cache
  | venv
  | docs
  | coverage_html
)/
'''

[tool.isort]
line_length = 120
known_first_party = 'src'
default_section = 'THIRDPARTY'
multi_line_output = 5
skip = 'venv'